name: Check release version

on: workflow_call

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - uses: actions/checkout@v4
      - name: Check version match
        run: |
          poetry_version="v$(poetry version -s)"
          echo "Poetry version: $poetry_version"
          echo "github ref version: ${{  github.ref_name }}"
          if [ $poetry_version != "${{  github.ref_name }}" ];then echo "Poetry version does not match git tag. Exiting" && exit 1; fi
