name: github page

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@a783c322200f1f9c8e6bfef3a0fb11ea0f18e9d # v1.4.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          poetry install --all-extras
      - run: |
          source .venv/bin/activate
          pdoc --output-directory=docs/api acme_dns_azure/___init___.py
          mv docs/api/___init___.html docs/api/index.html
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1ad65a89d7d0caa67b0f2ad94b5ab # v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e742a76521ecd2179dca91b429ee57537 # v3.0.1
        with:
          path: 'docs/api'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645ffc08ecf1fe1e5e4c4b25e0f21ca # v5.0.1
