name: Release

on:
  push:
    branches:
      - task/build-process
    # branches-ignore:
    #   - "!main"
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  unit_test:
    uses: ./.github/workflows/unit_test.yml
  integration_test:
    needs: [unit_test]
    uses: ./.github/workflows/integration_test.yml
    with:
      env: cicd
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    needs: [unit_test, integration_test]
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
