name: Release Flow

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  version_check:
    uses: ./.github/workflows/check_version.yml
  unit_test:
    needs: [version_check]
    uses: ./.github/workflows/unit_test.yml
  integration_test:
    needs: [unit_test]
    uses: ./.github/workflows/integration_test.yml
    secrets: inherit
  docs:
    needs: [integration_test]
    uses: ./.github/workflows/docs.yml
  publish_pypi:
    runs-on: ubuntu-latest
    needs: [docs]
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
  docker_build:
    needs: [publish_pypi]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
