name: Release

on:
  push:
    branches:
      - task/build-process
    # branches-ignore:
    #   - "!main"
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: unit-test
        uses: ./.github/workflows/unit_test.yml
      - name: integration-test
        uses: ./.github/workflows/integration_test
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
