name: Tag

on:
  pull_request:
    branches:
      - "tmp"
    types:
      - closed
    paths:
      - "pyproject.toml"

permissions:
  contents: write

jobs:
  create_tag:
    if: |
      ${{ (github.event.pull_request.merged == true) &&
      contains(github.event.pull_request.labels.*.name, 'automatic_bump') }}
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - uses: actions/checkout@v4
      - name: Receive version
        run: |
          new_version=$(poetry version -s)
          echo "new_version=${new_version}" >> $GITHUB_ENV
      - name: create git tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.new_version }}
          tag_prefix: v
  trigger_release:
    needs: [create_tag]
    uses: ./.github/workflows/release.yml
    secrets: inherit
