name: Tag

on:
  pull_request:
    branches:
      - "tmp"
    types:
      - closed
    paths:
      - "pyproject.toml"

permissions:
  contents: write

jobs:
  create_tag:
    if: |
      ${{ (github.event.pull_request.merged == true) &&
      contains(github.event.pull_request.labels.*.name, 'automatic_bump') }}
    runs-on: ubuntu-latest
    steps:
      - name: create git tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.head_commit.message }}
          tag_prefix: v
