name: unittest

on: [push, pull_request, workflow_call]

permissions:
  issues: write
  checks: write
  pull-requests: write

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          poetry install --all-extras
      - name: Test with pytest
        run: |
          poetry run coverage run
          poetry run coverage report
          poetry run coverage xml
      - uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb # v14
        with:
          minimum_coverage: 35
          fail_below_threshold: true
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
