name: Bump version

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    if: |
      (github.event.pull_request.merged == true) &&
      (contains(github.event.pull_request.labels.*.name, 'patch') ||
      contains(github.event.pull_request.labels.*.name, 'minor') ||
      contains(github.event.pull_request.labels.*.name, 'major') ||
      contains(github.event.pull_request.labels.*.name, 'prepatch') ||
      contains(github.event.pull_request.labels.*.name, 'preminor') ||
      contains(github.event.pull_request.labels.*.name, 'preminor') ||
      contains(github.event.pull_request.labels.*.name, 'prerelease'))
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Bump version
        run: |
          label_names='${{ toJSON(github.event.pull_request.labels) }}'
          relevant_labels=$(echo $label_names |  jq '[.[] | select((.name == "patch") or (.name == "minor") or (.name == "major") or (.name == "prepatch") or (.name == "preminor") or (.name == "premajor") or (.name == "prerelease"))]')
          length=$(echo $relevant_labels | jq 'length')
          if [ $length != 1 ]; then echo "More then one or none label has been defined. Exiting." && exit 1;fi
          version_bump=$(echo $relevant_labels | jq -r '.[] | .name')
          poetry -q self add poetry-bumpversion
          poetry version $version_bump
          cd examples/function
          poetry version $version_bump
          echo "version_bump=${version_bump}" >> $GITHUB_ENV
          new_version=$(poetry version -s)
          echo "new_version=${new_version}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660ad9427f7e98952847e9c83fb9c08c0 # v6.1.0
        with:
          title: 'Create release: ${{ env.version_bump }} ${{ env.new_version }}'
          labels: automatic_bump
